---

  - name: download nodejs rpm
    shell: 'yum install https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y'
    become: yes

  - name: install nodejs from nodesource
    shell: 'yum install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1'
    become: yes

  - name: install build essentials for native modules
    yum:
      name: gcc-c++
      state: present
    become: yes
