---


- name: "Installing packages"
  yum:
    name: "{{ packages }}"
    state: installed
  vars:
    packages:
    - java
    - zip
    - unzip
  become: yes

- name: Installing stable chrome
  shell: 'curl https://intoli.com/install-google-chrome.sh | bash'

- stat:
    path: ~/chromedriver
  register: chromedriver_exist

- name: Downloading chromedriver
  shell: 'wget https://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_linux64.zip'
  when: chromedriver_exist is defined and chromedriver_exist.stat.exists == false

- name: Unzip chromedriver
  shell: 'unzip chromedriver_linux64.zip'
  when: chromedriver_exist is defined and chromedriver_exist.stat.exists == false

- name: Moving chromedriver to usr bin
  shell: 'cp chromedriver /usr/bin'
  when: chromedriver_exist is defined and chromedriver_exist.stat.exists == false
  become: yes
- name: Moving chromedriver to usr local bin
  shell: 'cp chromedriver /usr/local/bin'
  when: chromedriver_exist is defined and chromedriver_exist.stat.exists == false
  become: yes
