---

  - name: reference nodesource on version 16
    shell: 'curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -'
    become: yes

  - name: install nodejs from nodesource
    shell: 'yum install nodejs --enablerepo=nodesource -y'
    become: yes

  - name: install build essentials for native modules
    yum:
      name: gcc-c++
      state: present
    become: yes
