---

- fail:
    msg: "service_id is required"
  when: service_id is not defined

- name: supervisord add service {{ service_id }}
  shell: /usr/bin/supervisorctl add {{ service_id }}
  args:
    chdir: /etc/supervisor/conf.d
  become: true

- name: supervisord start service {{ service_id }}
  shell: /usr/bin/supervisorctl start {{ service_id }}
  args:
    chdir: /etc/supervisor/conf.d
  become: true

- include_tasks: cronjob.yml
