---

- template:
    src: supervisord.conf
    dest: /etc/supervisor/conf.d/{{ service_id }}_supervisord.conf

- name: supervisord reread config
  shell: /usr/bin/supervisorctl reread
  args:
    chdir: /etc/supervisor/conf.d
  become: true
